export const projects = [{
        title: 'Example Title',
        description: "Example Description.",
        image: '/images/TJ.jpg',
        tags: ['Mongo', 'Express', 'React', 'Node'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 0,
    },
    {
        title: 'E-Example',
        description: "Example of life.",
        image: '/images/BCA.png',
        tags: ['React', 'JavaScript'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 1,
    },
    {
        title: 'E-Example',
        description: "Example of life.",
        image: '/images/BCA.png',
        tags: ['React', 'JavaScript'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 2,
    },
    {
        title: 'E-Example',
        description: "Example of life.",
        image: '/images/BCA.png',
        tags: ['React', 'JavaScript'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 3,
    },
    {
        title: 'E-Example',
        description: "Example of life.",
        image: '/images/BCA.png',
        tags: ['React', 'JavaScript'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 4,
    },
];

export const TimeLineData = [
    { year: 2017, text: 'Started my Product enthusiast journey', },
    { year: 2018, text: 'Worked as a freelance Product Designer', },
    { year: 2019, text: 'Learn something new in Product Research ', },
    { year: 2020, text: 'Developed projects from research to prototype', },
    { year: 2021, text: 'Started my own platform', },
];