export const projects = [{
        title: 'Transjakarta App',
        description: "Redesigning an android app helps people accommodate to achieve their needs by using the app and searching every spot in Jakarta.",
        image: '/images/TJ.jpg',
        tags: ['Balsamiq', 'Sketch'],
        source: '/TjContentPages',
        visit: 'https://google.com',
        id: 0,
    },
    {
        title: 'BCA CMS',
        description: "Design new Content Management System fraud mail for their workers. To achieve their needs by the team click the fraud content in their E-mail.",
        image: '/images/BCA.png',
        tags: ['Balsamiq', 'Sketch'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 1,
    },
    {
        title: 'Mass Rapid Transit Jakarta (Phase 1)',
        description: "Construct a fresh new interface for android application mobile, the second project build an interface for the MRT merchandise section, the third project build a CMS(Content Management System).",
        image: '/images/MRT.png',
        tags: ['Adobe XD', 'Sketch'],
        source: '',
        visit: 'https://google.com',
        id: 2,
    },
    {
        title: 'Bizzy Indonesia(Phoenix)',
        description: "Gathering some research topic about prototype design and create some customer content management system for bizzy project called Phoenix..",
        image: '/images/Bizzy Project.jpg',
        tags: ['Axure RP8', 'Sketch'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 3,
    },
    {
        title: 'Akeseleran',
        description: "Redesign some interface pages such as Portfolio Summary, Statistics Page,  Coupun Page ",
        image: '/images/Aksel.png',
        tags: ['Axure RP8', 'Sketch', 'Figma'],
        source: 'https://google.com',
        visit: 'https://google.com',
        id: 4,
    },
];

export const TimeLineData = [
    { year: 2017, text: 'Started my Product enthusiast journey', },
    { year: 2018, text: 'Worked as a freelance Product Designer', },
    { year: 2019, text: 'Learn something new in Product Research ', },
    { year: 2020, text: 'Developed projects from research to prototype', },
    { year: 2021, text: 'Started my own platform', },
];